---
apiVersion: v1
kind: Namespace
metadata:
  name: nim-example
  labels:
    name: nim-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-example
  namespace: nim-example
spec:
  selector:
    matchLabels:
      name: nim-example
  template:
    metadata:
      labels:
        name: nim-example
    spec:
      containers:
        - name: nim-example
          image: thisthatdc/nim-example:v0.1.1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: "delta"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nim-example
  namespace: nim-example
spec:
  type: NodePort
  selector:
    name: nim-example
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
      nodePort: 30100
