---
apiVersion: v1
kind: Namespace
metadata:
  name: nim-example
  labels:
    name: nim-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-example
  namespace: nim-example
spec:
  selector:
    matchLabels:
      name: nim-example
  template:
    metadata:
      labels:
        name: nim-example
    spec:
      containers:
        - name: nim-example
          image: dtdemos/nim-example:0.1.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NIM_MODEL
              value: "meta/llama-3.3-70b-instruct"
            - name: NIM_EMBEDDING_MODEL
              value: "text-embedding-ada-002"
            - name: CLIENT_BASE_URL
              value: "http://llama-33-70b-instruct.nim-service:8000/v1/"
            - name: LANGCHAIN_LLM_BASE_URL
              value: "http://llama-33-70b-instruct.nim-service:8000/v1/"
            - name: LANGCHAIN_EMBEDDING_BASE_URL
              value: "http://llama-33-70b-instruct.nim-service:8000/v1/"
            - name: DYNATRACE_OLTP_URL
              value: "https://**ADJUST**.live.dynatrace.com/api/v2/otlp"
            - name: DYNATRACE_API_TOKEN
              value: "**ADJUST**"
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: "delta"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nim-example
  namespace: nim-service
spec:
  type: LoadBalancer 
  selector:
    name: nim-example
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP
      nodePort: 30100
